class EPCISTraceabilityResolver {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: GetEPCISQueryInterfaceURL
        // [OT_AutoGenerated_FROM]: GetEPCISQueryInterfaceURL
        // [OT_AutoGenerated_HASH]: cfe498014dbe5f8cd41a7c3f02aa5c8982c0db7c647eec0b182f74aecaabcb4a
        fun GetEPCISQueryInterfaceURL(DigitalLinkQueryOptions options, EPC epc, HttpClient client): Task`1 {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: GetEPCISQueryInterfaceURL
        // [OT_AutoGenerated_FROM]: GetEPCISQueryInterfaceURL
        // [OT_AutoGenerated_HASH]: 742ee47ca8c6fbba041e5c3a5f3486915affe5e8c7dbc636bd9b882d165f7e73
        fun GetEPCISQueryInterfaceURL(DigitalLinkQueryOptions options, PGLN pgln, HttpClient client): Task`1 {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: Traceback
        // [OT_AutoGenerated_FROM]: Traceback
        // [OT_AutoGenerated_HASH]: 7c5a4d1f6f8384ccd941f9642964fa256dd97e65c46130af71f4ebcf85c2566e
        fun Traceback(EPCISQueryInterfaceOptions options, EPC epc, HttpClient client, EPCISQueryParameters additionalParameters): Task`1 {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: QueryEvents
        // [OT_AutoGenerated_FROM]: QueryEvents
        // [OT_AutoGenerated_HASH]: c5f3a86e0819e89bf51b534358e8caf31855ee575662c1f2acae84f9a5d1c758
        fun QueryEvents(EPCISQueryInterfaceOptions options, EPCISQueryParameters parameters, HttpClient client): Task`1 {
            // Method body goes here
        }
}
