import java.lang.reflect.Type
class MasterDataResolver {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: ResolveMasterData
        // [OT_AutoGenerated_FROM]: ResolveMasterData
        // [OT_AutoGenerated_HASH]: 6e9f91505ff3e29d18a3e9cf21193fb0dac6a1016c7aa38f60db83a27d0bc677
        fun ResolveMasterData(options: DigitalLinkQueryOptions, doc: EPCISBaseDocument, client: HttpClient): Task {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: ResolveMasterData
        // [OT_AutoGenerated_FROM]: ResolveMasterData
        // [OT_AutoGenerated_HASH]: 947ca7628d8d109072a7ea8e151c6cc955eb42a962541e89ffb3fe601014a831
        fun ResolveMasterData(options: DigitalLinkQueryOptions, doc: EPCISBaseDocument, client: HttpClient): Task {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: ResolveTradeitem
        // [OT_AutoGenerated_FROM]: ResolveTradeitem
        // [OT_AutoGenerated_HASH]: e70402e5b55d492a0240f2a48e1f79e4f714b0d3fe4e726c74be8403e24c83aa
        fun ResolveTradeitem(options: DigitalLinkQueryOptions, gtin: GTIN, doc: EPCISBaseDocument, client: HttpClient): Task {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: ResolveLocation
        // [OT_AutoGenerated_FROM]: ResolveLocation
        // [OT_AutoGenerated_HASH]: 5216a188ad6c8b21074de97ea041ca34382c81678199671551fbae0753ef0ee4
        fun ResolveLocation(options: DigitalLinkQueryOptions, gln: GLN, doc: EPCISBaseDocument, client: HttpClient): Task {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: ResolveTradingParty
        // [OT_AutoGenerated_FROM]: ResolveTradingParty
        // [OT_AutoGenerated_HASH]: a454b13aacb6b8a9f6e60e314ddf5e1f35530729d3190d2fb00ac09266360eaf
        fun ResolveTradingParty(options: DigitalLinkQueryOptions, pgln: PGLN, doc: EPCISBaseDocument, client: HttpClient): Task {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: ResolveTradeitem
        // [OT_AutoGenerated_FROM]: ResolveTradeitem
        // [OT_AutoGenerated_HASH]: 20b441ead5e4ab0b40fc1b9fb949824f6f4e47db6819b1e27a8a8a496f354c19
        fun ResolveTradeitem(options: DigitalLinkQueryOptions, gtin: GTIN, doc: EPCISBaseDocument, client: HttpClient): Task {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: ResolveLocation
        // [OT_AutoGenerated_FROM]: ResolveLocation
        // [OT_AutoGenerated_HASH]: 5d5e7440ecbf9ed615636ee083122bfd6a345d0140b163e23ed442b6893f03f8
        fun ResolveLocation(options: DigitalLinkQueryOptions, gln: GLN, doc: EPCISBaseDocument, client: HttpClient): Task {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: ResolveTradingParty
        // [OT_AutoGenerated_FROM]: ResolveTradingParty
        // [OT_AutoGenerated_HASH]: 07385c53e9f7e902f755e06256f72bc0a951cc0c27fdeea23149432daea9844c
        fun ResolveTradingParty(options: DigitalLinkQueryOptions, pgln: PGLN, doc: EPCISBaseDocument, client: HttpClient): Task {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: ResolveTradeitem
        // [OT_AutoGenerated_FROM]: ResolveTradeitem
        // [OT_AutoGenerated_HASH]: 90ee2bc5a5095863487764b8ace445cdf75a6bd03fd371cba8f425615ee25dbd
        fun ResolveTradeitem(options: DigitalLinkQueryOptions, gtin: GTIN, client: HttpClient): Task`1 {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: ResolveLocation
        // [OT_AutoGenerated_FROM]: ResolveLocation
        // [OT_AutoGenerated_HASH]: 27993daad2aad8480f9996492b6ff67458bf67753c271bfc23dd2799cd5a0c30
        fun ResolveLocation(options: DigitalLinkQueryOptions, gln: GLN, client: HttpClient): Task`1 {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: ResolveTradingParty
        // [OT_AutoGenerated_FROM]: ResolveTradingParty
        // [OT_AutoGenerated_HASH]: 1931ccd533d819224a444974efad2f404f57efd03168144c63780d310c92d08e
        fun ResolveTradingParty(options: DigitalLinkQueryOptions, pgln: PGLN, client: HttpClient): Task`1 {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: ResolverMasterDataItem
        // [OT_AutoGenerated_FROM]: ResolverMasterDataItem
        // [OT_AutoGenerated_HASH]: 0107c995c56b4b0d923de4255440d5bf80ebf310730690934c8abb5067d03150
        fun ResolverMasterDataItem(options: DigitalLinkQueryOptions, relativeURL: String, client: HttpClient): Task`1 {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: ResolveMasterDataItem
        // [OT_AutoGenerated_FROM]: ResolveMasterDataItem
        // [OT_AutoGenerated_HASH]: 39b535f0d5166d781cfe8189d2af914626d2d54ac8cf86b88b4c9add681c4bc3
        fun ResolveMasterDataItem(type: Type, options: DigitalLinkQueryOptions, relativeURL: String, httpClient: HttpClient): Task`1 {
            // Method body goes here
        }
}
