class OTLogger {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: Error
        // [OT_AutoGenerated_FROM]: Error
        // [OT_AutoGenerated_HASH]: 130de2b583eaf82d312365d66007ec3c45c41c1cafe4bffc8072d1446234946b
        fun Error(ex: Exception): Void {
            // Method body goes here
        }
}
