class Setup {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: Initialize
        // [OT_AutoGenerated_FROM]: Initialize
        // [OT_AutoGenerated_HASH]: e4971043b7e9d90842d5066a95e44e8bfa01260cfc9f235ce24dffe334911d53
        fun Initialize(): Void {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: RegisterEventProfile
        // [OT_AutoGenerated_FROM]: RegisterEventProfile
        // [OT_AutoGenerated_HASH]: 6801281720fb1965864d81ea4f55d70b6eece264e708e0ed9de57b43b9ace160
        fun RegisterEventProfile(OpenTraceabilityEventProfile profile): Void {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: RegisterMasterDataType
        // [OT_AutoGenerated_FROM]: RegisterMasterDataType
        // [OT_AutoGenerated_HASH]: c3c9d762401605cea95167f2d80bc6f098219229a19c3be9a60c768d1e9a7756
        fun RegisterMasterDataType(Type defaultFor): Void {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: RegisterMasterDataType
        // [OT_AutoGenerated_FROM]: RegisterMasterDataType
        // [OT_AutoGenerated_HASH]: c70febbb7f0c22ef792a4f61c49e0b2a6b1aeacf5aa966c116c47a684fad641e
        fun RegisterMasterDataType(): Void {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: GetMasterDataTypeDefault
        // [OT_AutoGenerated_FROM]: GetMasterDataTypeDefault
        // [OT_AutoGenerated_HASH]: 2c52ba50bf21d6eaa0fe8fdbf8b872fc5c2de9e4edad5495572f035215f13fd9
        fun GetMasterDataTypeDefault(Type type): Type {
            // Method body goes here
        }
}
