class EPC {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: DetectEPCIssue
        // [OT_AutoGenerated_FROM]: DetectEPCIssue
        // [OT_AutoGenerated_HASH]: fabfd85a5f42531d206564a554c394d7bb85c87c7464e470e3f3135e8cba293a
        fun DetectEPCIssue(String epcStr): String {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: TryParse
        // [OT_AutoGenerated_FROM]: TryParse
        // [OT_AutoGenerated_HASH]: ff73a0fef4e353177b2d0c389da3a48ecfeb64a41473d04d84aadcad3fd36c6e
        fun TryParse(String epcStr, EPC& epc, String& error): Boolean {
            // Method body goes here
        }
}
