class GLN {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: IsGLN
        // [OT_AutoGenerated_FROM]: IsGLN
        // [OT_AutoGenerated_HASH]: b7872d9850aa771cbef2078a1ef5e5f99312d6839c3217d25a486cae0b3d8828
        fun IsGLN(String glnStr): Boolean {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: DetectGLNIssue
        // [OT_AutoGenerated_FROM]: DetectGLNIssue
        // [OT_AutoGenerated_HASH]: 4d7ad6899fa8c9c7c98eced3c5f2240bc0bb0925c9ad291f66e2686cd33a7e21
        fun DetectGLNIssue(String glnStr): String {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: TryParse
        // [OT_AutoGenerated_FROM]: TryParse
        // [OT_AutoGenerated_HASH]: 4a0fda930bc9f16181ac917c6ad1ca9f3e8762d855ef3fea7a0c27c9a1e4619a
        fun TryParse(String glnStr, GLN& gln, String& error): Boolean {
            // Method body goes here
        }
}
