class GS1Util {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: CalculateGTIN14CheckSum
        // [OT_AutoGenerated_FROM]: CalculateGTIN14CheckSum
        // [OT_AutoGenerated_HASH]: 770e21a625396148a62386f0a4252ef27923e6b78ea3f755b1dec2e1ed3bd23f
        fun CalculateGTIN14CheckSum(String strGS): Char {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: CalculateGLN13CheckSum
        // [OT_AutoGenerated_FROM]: CalculateGLN13CheckSum
        // [OT_AutoGenerated_HASH]: 8ef939885fbeccf175193333f7cf08266818ca99a0dd4bb65a7d9ba6a27b8eea
        fun CalculateGLN13CheckSum(String strGS): Char {
            // Method body goes here
        }
}
