class GTIN {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: TryParse
        // [OT_AutoGenerated_FROM]: TryParse
        // [OT_AutoGenerated_HASH]: c342ac915369d694416c0d44c0e36b06cbda3124c34377586d23bf1760808190
        fun TryParse(gtinStr: String, gtin: GTIN&, error: String&): Boolean {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: DetectGTINIssue
        // [OT_AutoGenerated_FROM]: DetectGTINIssue
        // [OT_AutoGenerated_HASH]: ca7b8f95eb5af81e04dc83fb077377e5601fc81564953c394fdf1c5666b033b3
        fun DetectGTINIssue(gtinStr: String): String {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: IsGTIN
        // [OT_AutoGenerated_FROM]: IsGTIN
        // [OT_AutoGenerated_HASH]: d513b8d38845be36e7bb46e4a1efe363c591aa6cc5385091e56ef19cd230a7c9
        fun IsGTIN(gtinStr: String): Boolean {
            // Method body goes here
        }
}
