class PGLN {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: IsPGLN
        // [OT_AutoGenerated_FROM]: IsPGLN
        // [OT_AutoGenerated_HASH]: d64181b597ba33e320254da14d0cdb8ed0cfb65ca680b40c7f5ee23039a2c079
        fun IsPGLN(pglnStr: String): Boolean {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: DetectPGLNIssue
        // [OT_AutoGenerated_FROM]: DetectPGLNIssue
        // [OT_AutoGenerated_HASH]: caaa7ef2349777751150da91cbe8b1d3fd01a0a633abfd4eca4fb6c0fe411880
        fun DetectPGLNIssue(pglnStr: String): String {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: TryParse
        // [OT_AutoGenerated_FROM]: TryParse
        // [OT_AutoGenerated_HASH]: 27f670a1e4dfeecb778a3c265bd3ee47a4cc39ca3f83bfedea96e4ffca40b1c5
        fun TryParse(pglnStr: String, pgln: PGLN&, error: String&): Boolean {
            // Method body goes here
        }
}
