class OpenTraceabilityJsonLDMapper {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: ToJson
        // [OT_AutoGenerated_FROM]: ToJson
        // [OT_AutoGenerated_HASH]: c15738b533dbde8172db52047667edba17a6e67fa20f5b02cd6dda22fbdc5c2e
        fun ToJson(Object value, Dictionary`2 namespacesReversed, Boolean required): JToken {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: FromJson
        // [OT_AutoGenerated_FROM]: FromJson
        // [OT_AutoGenerated_HASH]: c35c460717f3777eeabbf0480cd01e634c86f3566c21f4eb1e7775b330b3f65c
        fun FromJson(JToken json, Dictionary`2 namespaces): T {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: FromJson
        // [OT_AutoGenerated_FROM]: FromJson
        // [OT_AutoGenerated_HASH]: 4e508f019fe8e381aeedccfade6b34b84a6ddfca3cb6c52a328c94677ef9aa7c
        fun FromJson(JToken json, Type type, Dictionary`2 namespaces): Object {
            // Method body goes here
        }
}
