import java.lang.reflect.Type
class OpenTraceabilityJsonLDMapper {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: ToJson
        // [OT_AutoGenerated_FROM]: ToJson
        // [OT_AutoGenerated_HASH]: c15738b533dbde8172db52047667edba17a6e67fa20f5b02cd6dda22fbdc5c2e
        fun ToJson(value: Object, namespacesReversed: Dictionary`2, required: Boolean): JToken {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: FromJson
        // [OT_AutoGenerated_FROM]: FromJson
        // [OT_AutoGenerated_HASH]: c35c460717f3777eeabbf0480cd01e634c86f3566c21f4eb1e7775b330b3f65c
        fun FromJson(json: JToken, namespaces: Dictionary`2): T {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: FromJson
        // [OT_AutoGenerated_FROM]: FromJson
        // [OT_AutoGenerated_HASH]: 4e508f019fe8e381aeedccfade6b34b84a6ddfca3cb6c52a328c94677ef9aa7c
        fun FromJson(json: JToken, type: Type, namespaces: Dictionary`2): Object {
            // Method body goes here
        }
}
