package mappers
import com.fasterxml.jackson.core.JsonToken
import java.util.*
import java.lang.reflect.Type
class OpenTraceabilityJsonLDMapper<T> {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: ToJson
        // [OT_AutoGenerated_FROM]: ToJson
        // [OT_AutoGenerated_HASH]: c15738b533dbde8172db52047667edba17a6e67fa20f5b02cd6dda22fbdc5c2e
        fun ToJson(value: Object, namespacesReversed: Dictionary<String, String>, required: Boolean): JsonToken {
            // Method body goes here
            return JsonToken()
        }

        // [OT_AutoGenerated_FROM]: FromJson
        // [OT_AutoGenerated_FROM]: FromJson
        // [OT_AutoGenerated_HASH]: c35c460717f3777eeabbf0480cd01e634c86f3566c21f4eb1e7775b330b3f65c
        fun<T> FromJson(json: JsonToken, namespaces: Dictionary<String, String>): T {
            // Method body goes here
            return T()
        }

        // [OT_AutoGenerated_FROM]: FromJson
        // [OT_AutoGenerated_FROM]: FromJson
        // [OT_AutoGenerated_HASH]: 4e508f019fe8e381aeedccfade6b34b84a6ddfca3cb6c52a328c94677ef9aa7c
        fun FromJson(json: JsonToken, type: Type, namespaces: Dictionary<String, String>): Object {
            // Method body goes here
            return Object()
        }
}
