class OpenTraceabilityXmlMapper {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: ToXml
        // [OT_AutoGenerated_FROM]: ToXml
        // [OT_AutoGenerated_HASH]: 45a48e147553d22fd57f1a067ce4b3b0559d2c50398b05ef1472d4821b3badd5
        fun ToXml(String xname, Object value, EPCISVersion version, Boolean required): XElement {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: FromXml
        // [OT_AutoGenerated_FROM]: FromXml
        // [OT_AutoGenerated_HASH]: 0879539c6234f6df5f5d0686a833622434cc11919f453f32af5dc858f1f7583f
        fun FromXml(XElement x, EPCISVersion version): T {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: FromXml
        // [OT_AutoGenerated_FROM]: FromXml
        // [OT_AutoGenerated_HASH]: 91d008b87d793350a80538f072e2d36dd48f7a25b35bcd1b7952f546146a5dfd
        fun FromXml(XElement x, Type type, EPCISVersion version): Object {
            // Method body goes here
        }
}
