import java.lang.reflect.Type
class OTMappingTypeInformation {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: GetXmlTypeInfo
        // [OT_AutoGenerated_FROM]: GetXmlTypeInfo
        // [OT_AutoGenerated_HASH]: 38fd5d65824f41ef03c75e8ca27ab7a53e41d01228322cd7c057e1c322042565
        fun GetXmlTypeInfo(t: Type): OTMappingTypeInformation {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: GetJsonTypeInfo
        // [OT_AutoGenerated_FROM]: GetJsonTypeInfo
        // [OT_AutoGenerated_HASH]: 72db95bf77ce5afab0ad61c59ce84b2cd1d4809b773acbd8509f432c79e37277
        fun GetJsonTypeInfo(t: Type): OTMappingTypeInformation {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: GetMasterDataXmlTypeInfo
        // [OT_AutoGenerated_FROM]: GetMasterDataXmlTypeInfo
        // [OT_AutoGenerated_HASH]: 99b5e8e838ed46dfa9cf7ff355e98b53fb8acfd65b12e9f853b6d3b9b1f0b358
        fun GetMasterDataXmlTypeInfo(t: Type): OTMappingTypeInformation {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: GetMasterDataJsonTypeInfo
        // [OT_AutoGenerated_FROM]: GetMasterDataJsonTypeInfo
        // [OT_AutoGenerated_HASH]: c684a675532485d91363c801c4ceff50a67ccaa60f6dd5d956f5d64af8c289ac
        fun GetMasterDataJsonTypeInfo(t: Type): OTMappingTypeInformation {
            // Method body goes here
        }
}
