class EPCISDocumentBaseJsonMapper {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: ReadJSON
        // [OT_AutoGenerated_FROM]: ReadJSON
        // [OT_AutoGenerated_HASH]: 33a018d94856527cdbc0f71f55ef230c5bf6de5c7eb5a610d53c6fd3a02dc142
        fun ReadJSON(String strValue, JObject& json, Boolean checkSchema): T {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: WriteJson
        // [OT_AutoGenerated_FROM]: WriteJson
        // [OT_AutoGenerated_HASH]: bcd2ef4ad4739f33c00153c5d20a426e3f1736693deaaa8d39b6d4a912d1ba9b
        fun WriteJson(EPCISBaseDocument doc, String epcisNS, String docType): JObject {
            // Method body goes here
        }
}
