package mappers.epcis.json
import com.intellij.json.psi.JsonObject
import models.identifiers.*
import models.events.*
class EPCISJsonMasterDataReader {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: ReadMasterData
        // [OT_AutoGenerated_FROM]: ReadMasterData
        // [OT_AutoGenerated_HASH]: 4d839615eb1bab24d921f4e37da0d69b52cea70f15f297a0ffdfbe519d653c5a
        fun ReadMasterData(doc: EPCISBaseDocument, jMasterData: JsonObject) {
            // Method body goes here
        }
}
