package mappers.epcis.json
import com.intellij.json.psi.JsonObject
import models.identifiers.*
import models.events.*
import java.lang.reflect.Type
class EPCISDocumentBaseJsonMapper<T> {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: ReadJSON
        // [OT_AutoGenerated_FROM]: ReadJSON
        // [OT_AutoGenerated_HASH]: 33a018d94856527cdbc0f71f55ef230c5bf6de5c7eb5a610d53c6fd3a02dc142
        fun<T> ReadJSON(strValue: String, json: JObject, checkSchema: Boolean): T {
            // Method body goes here
            return T()
        }

        // [OT_AutoGenerated_FROM]: WriteJson
        // [OT_AutoGenerated_FROM]: WriteJson
        // [OT_AutoGenerated_HASH]: bcd2ef4ad4739f33c00153c5d20a426e3f1736693deaaa8d39b6d4a912d1ba9b
        fun WriteJson(doc: EPCISBaseDocument, epcisNS: String, docType: String): JsonObject {
            // Method body goes here
            return JsonObject()
        }
}
