package mappers.epcis.json
import com.intellij.json.psi.JsonObject
import models.identifiers.*
import models.events.*
class EPCISJsonMasterDataWriter {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: WriteMasterData
        // [OT_AutoGenerated_FROM]: WriteMasterData
        // [OT_AutoGenerated_HASH]: aebcd25bce951501441b654b6f98ed0e04cd1309386d571f7a77c1289cd4fb3c
        fun WriteMasterData(jDoc: JsonObject, doc: EPCISBaseDocument) {
            // Method body goes here
        }
}
