class EPCISDocumentBaseXMLMapper {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: ReadXml
        // [OT_AutoGenerated_FROM]: ReadXml
        // [OT_AutoGenerated_HASH]: b4a052979f404721de2341cfa1c57bfe1dcb675acb48199c5b340b93f03b290d
        fun ReadXml(strValue: String, xDoc: XDocument&): T {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: WriteXml
        // [OT_AutoGenerated_FROM]: WriteXml
        // [OT_AutoGenerated_HASH]: f855a0b505f8fbec94667ed6b49a0c9d585a91001ad277357663ad8396dcb673
        fun WriteXml(doc: EPCISBaseDocument, epcisNS: String, rootEleName: String): XDocument {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: ValidateEPCISDocumentSchema
        // [OT_AutoGenerated_FROM]: ValidateEPCISDocumentSchema
        // [OT_AutoGenerated_HASH]: 1ee9806ee3d0d81d579e2d94f7613e540966f33c8657733a94f7ac08e08da749
        fun ValidateEPCISDocumentSchema(xdoc: XDocument, version: EPCISVersion): Void {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: ValidateEPCISQueryDocumentSchema
        // [OT_AutoGenerated_FROM]: ValidateEPCISQueryDocumentSchema
        // [OT_AutoGenerated_HASH]: 0e3d93616d8262df1af337d2d8611a2590aa344dbd917890ff8758573a4eeb1d
        fun ValidateEPCISQueryDocumentSchema(xdoc: XDocument, version: EPCISVersion): Void {
            // Method body goes here
        }
}
