class EPCISXmlMasterDataReader {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: ReadMasterData
        // [OT_AutoGenerated_FROM]: ReadMasterData
        // [OT_AutoGenerated_HASH]: 8c792e288f97808217366ae039110a777c223a4a42487865d76af9a89a5d523f
        fun ReadMasterData(doc: EPCISBaseDocument, xMasterData: XElement): Void {
            // Method body goes here
        }
}
