class EPCISXmlMasterDataWriter {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: WriteMasterData
        // [OT_AutoGenerated_FROM]: WriteMasterData
        // [OT_AutoGenerated_HASH]: 24b51b9029d768c055af721ca6f16b818e201a1fa0cbd359e7ab660f893dd94a
        fun WriteMasterData(XElement xDocument, EPCISBaseDocument doc): Void {
            // Method body goes here
        }
}
