package utility
import java.util.*
class Countries {
    var CountryList: List<Country> = ArrayList<Country>()
    companion object{
        var CountryList: List<Country> = ArrayList<Country>()
    }

        // [OT_AutoGenerated_FROM]: FromAbbreviation
        // [OT_AutoGenerated_FROM]: FromAbbreviation
        // [OT_AutoGenerated_HASH]: e712ad3419818f116326fc1367dc6693653dae5af711db55ed4ce82248e91083
        fun FromAbbreviation(code: String): Country {
            // Method body goes here
            return Country()
        }

        // [OT_AutoGenerated_FROM]: FromAlpha3
        // [OT_AutoGenerated_FROM]: FromAlpha3
        // [OT_AutoGenerated_HASH]: 5174e36533a15884689ae1da89ce07e23b052b23547af397b89e8b83bed2a4c7
        fun FromAlpha3(code: String): Country {
            // Method body goes here
            return Country()
        }

        // [OT_AutoGenerated_FROM]: FromCountryName
        // [OT_AutoGenerated_FROM]: FromCountryName
        // [OT_AutoGenerated_HASH]: 6b152eb8903fccb8e91c6cb8ba47f61099412de72f8256b2006838cf592d68ec
        fun FromCountryName(name: String): Country {
            // Method body goes here
            return Country()
        }

        // [OT_AutoGenerated_FROM]: FromCountryIso
        // [OT_AutoGenerated_FROM]: FromCountryIso
        // [OT_AutoGenerated_HASH]: 7f3d70dfd32b00560df3509746ef9d041e93f9f8bbf0fdfe6c582fd0f8e282c5
        fun FromCountryIso(iso: Int): Country {
            // Method body goes here
            return Country()
        }

        // [OT_AutoGenerated_FROM]: Parse
        // [OT_AutoGenerated_FROM]: Parse
        // [OT_AutoGenerated_HASH]: beeac516893f83842335a2a89ae6ae10426954047be57eecdec5f94fbd68cac4
        fun Parse(strValue: String): Country {
            // Method body goes here
            return Country()
        }
}
