package utility
import java.util.*
class DictionaryExtensions {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: Reverse
        // [OT_AutoGenerated_FROM]: Reverse
        // [OT_AutoGenerated_HASH]: 3853664f0172a2e707c2fcd633c53cc6b501683b67871f86fcc61e39152e88c6
        fun<TValue,TKey> Reverse(source: Dictionary<TKey, TValue>): Dictionary<TValue, TKey> {
            // Method body goes here
            return Dictionary<TValue, TKey>()
        }
}
