class DoubleExtensions {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: Round
        // [OT_AutoGenerated_FROM]: Round
        // [OT_AutoGenerated_HASH]: 8f50089e2dd502dfd9e1572366d9ded556d34901d3261c90b5261e424d209c8e
        fun Round(val: Double): Double {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: Round
        // [OT_AutoGenerated_FROM]: Round
        // [OT_AutoGenerated_HASH]: b48a19ce62edf5858229dc77ffd68a64dd00b744b3fd5f0cb4614343a4291058
        fun Round(val: Double?): Double? {
            // Method body goes here
        }
}
