class EnumUtil {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: GetEnumDescription
        // [OT_AutoGenerated_FROM]: GetEnumDescription
        // [OT_AutoGenerated_HASH]: ca17168ea667177adaaddd784a6a4fe812d1adf3e52b2eff74db118efb69290e
        fun GetEnumDescription(Object value): String {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: GetEnumDisplayName
        // [OT_AutoGenerated_FROM]: GetEnumDisplayName
        // [OT_AutoGenerated_HASH]: 1960e875577a83d41e98093874222ba2f18fb3fab2ea9c45998f7a6308572d28
        fun GetEnumDisplayName(Object value): String {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: GetEnumAttributes
        // [OT_AutoGenerated_FROM]: GetEnumAttributes
        // [OT_AutoGenerated_HASH]: 30747917b507177bdbc08fdb188ab0bae4c5541a5d356858dc58cb7d81afc099
        fun GetEnumAttributes(Object value): List<T> {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: GetValues
        // [OT_AutoGenerated_FROM]: GetValues
        // [OT_AutoGenerated_HASH]: 825d84ee824db99567d3aff384f6be5adb748bb4464f1bedfd55ed6019287618
        fun GetValues(): IEnumerable`1 {
            // Method body goes here
        }
}
