package utility
import java.net.http.HttpClient
class HttpClientPool {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: GetClient
        // [OT_AutoGenerated_FROM]: GetClient
        // [OT_AutoGenerated_HASH]: 0fe1f62d5b9b02ef43958107b4f30ba11f3043ac06d806b301471a525779d1d6
        fun GetClient(): Utility.LimitedPoolItem<HttpClient> {
            // Method body goes here
            return Utility.LimitedPoolItem<HttpClient>()
        }
}
