package utility
import com.intellij.json.psi.JSONObject
import com.fasterxml.jackson.core.JsonToken
import java.util.*
class JsonContextHelper {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: GetJsonLDContext
        // [OT_AutoGenerated_FROM]: GetJsonLDContext
        // [OT_AutoGenerated_HASH]: 0da31b5e54ae73f92db105c84d3b55727c170d9744d5b28787d102897c873492
        fun GetJsonLDContext(contextURL: String): JSONObject {
            // Method body goes here
            return JSONObject()
        }

        // [OT_AutoGenerated_FROM]: ScrapeNamespaces
        // [OT_AutoGenerated_FROM]: ScrapeNamespaces
        // [OT_AutoGenerated_HASH]: ad1d32b17e0731415c1725c85aec170f0e1656e10822d8529771e5df29ca4002
        fun<String> ScrapeNamespaces(jContext: JSONObject): System.Collections.Generic.Dictionary<String,String> {
            // Method body goes here
            return System.Collections.Generic.Dictionary<String,String>()
        }

        // [OT_AutoGenerated_FROM]: IsNamespace
        // [OT_AutoGenerated_FROM]: IsNamespace
        // [OT_AutoGenerated_HASH]: 134a4d6d825548c0be8d671646bbc304c2ec7b3ee9a79c92decf0a6dc4596dc7
        fun IsNamespace(value: String): Boolean {
            // Method body goes here
            return 1==1
        }

        // [OT_AutoGenerated_FROM]: ExpandVocab
        // [OT_AutoGenerated_FROM]: ExpandVocab
        // [OT_AutoGenerated_HASH]: ce9bb2e4d94524fc9b17b3681edd5431add8de9a5ff629809ccff31acfa236c2
        fun ExpandVocab(json: JsonToken, jcontext: JSONObject, namespaces: System.Collections.Generic.Dictionary<String,String>, jvocabcontext: JSONObject): JsonToken {
            // Method body goes here
            return JsonToken()
        }

        // [OT_AutoGenerated_FROM]: CompressVocab
        // [OT_AutoGenerated_FROM]: CompressVocab
        // [OT_AutoGenerated_HASH]: 19a80dbc5ae86ff330e604e2abb8dae45c211b52946478036f6bf2ab3466d9c3
        fun CompressVocab(json: JsonToken, jcontext: JSONObject, namespaces: System.Collections.Generic.Dictionary<String,String>, jvocabcontext: JSONObject): JsonToken {
            // Method body goes here
            return JsonToken()
        }
}
