class JsonContextHelper {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: GetJsonLDContext
        // [OT_AutoGenerated_FROM]: GetJsonLDContext
        // [OT_AutoGenerated_HASH]: 0da31b5e54ae73f92db105c84d3b55727c170d9744d5b28787d102897c873492
        fun GetJsonLDContext(String contextURL): JObject {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: ScrapeNamespaces
        // [OT_AutoGenerated_FROM]: ScrapeNamespaces
        // [OT_AutoGenerated_HASH]: ad1d32b17e0731415c1725c85aec170f0e1656e10822d8529771e5df29ca4002
        fun ScrapeNamespaces(JObject jContext): Dictionary`2 {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: IsNamespace
        // [OT_AutoGenerated_FROM]: IsNamespace
        // [OT_AutoGenerated_HASH]: 134a4d6d825548c0be8d671646bbc304c2ec7b3ee9a79c92decf0a6dc4596dc7
        fun IsNamespace(String value): Boolean {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: ExpandVocab
        // [OT_AutoGenerated_FROM]: ExpandVocab
        // [OT_AutoGenerated_HASH]: ce9bb2e4d94524fc9b17b3681edd5431add8de9a5ff629809ccff31acfa236c2
        fun ExpandVocab(JToken json, JObject jcontext, Dictionary`2 namespaces, JObject jvocabcontext): JToken {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: CompressVocab
        // [OT_AutoGenerated_FROM]: CompressVocab
        // [OT_AutoGenerated_HASH]: 19a80dbc5ae86ff330e604e2abb8dae45c211b52946478036f6bf2ab3466d9c3
        fun CompressVocab(JToken json, JObject jcontext, Dictionary`2 namespaces, JObject jvocabcontext): JToken {
            // Method body goes here
        }
}
