class JsonSchemaChecker {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: IsValid
        // [OT_AutoGenerated_FROM]: IsValid
        // [OT_AutoGenerated_HASH]: a0c9b281f18a8dc2d15671bd1020d616fe2b9c70670ed2d0998d46f15e77922f
        fun IsValid(String jsonStr, String schemaURL, List`1& errors): Boolean {
            // Method body goes here
        }
}
