class Measurement {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: Parse
        // [OT_AutoGenerated_FROM]: Parse
        // [OT_AutoGenerated_HASH]: fd58e01beb91b3b752282a68df87a5faeb0fc3c747e29170a1f10667687d1ae1
        fun Parse(String strValue): Measurement {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: TryParse
        // [OT_AutoGenerated_FROM]: TryParse
        // [OT_AutoGenerated_HASH]: 5c09ff8d023d7a0c62a0545a7bc98f40dfbfaaeeba3ef086f9a2972610445c94
        fun TryParse(String strValue): Measurement {
            // Method body goes here
        }
}
