class StaticData {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: ReadData
        // [OT_AutoGenerated_FROM]: ReadData
        // [OT_AutoGenerated_HASH]: e12b03363445bb3f3789091366c350d6adfb15735301a62940fcb0c390459cd5
        fun ReadData(path: String): String {
            // Method body goes here
        }
}
