package utility
import java.util.*
import java.net.URI
import java.time.OffsetDateTime
class StringExtensions {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: IsOnlyDigits
        // [OT_AutoGenerated_FROM]: IsOnlyDigits
        // [OT_AutoGenerated_HASH]: b8b88503dd67548e4d22a9e0eb5a2fff97ebe3f8e2200ffc14ff0628be383e94
        fun IsOnlyDigits(str: String): Boolean {
            // Method body goes here
            return 1==1
        }

        // [OT_AutoGenerated_FROM]: TryConvertToDateTimeOffset
        // [OT_AutoGenerated_FROM]: TryConvertToDateTimeOffset
        // [OT_AutoGenerated_HASH]: b10698a28c0785ff160fba8fba7234eede77a4234df34759e91e58689f779101
        fun TryConvertToDateTimeOffset(str: String): OffsetDateTime? {
            // Method body goes here
            return OffsetDateTime.now()
        }

        // [OT_AutoGenerated_FROM]: IsURICompatibleChars
        // [OT_AutoGenerated_FROM]: IsURICompatibleChars
        // [OT_AutoGenerated_HASH]: 1b2f03afd3fdd1c0d31e0ef2656b6442364974b5d44aa8e379d9eb537202815f
        fun IsURICompatibleChars(str: String): Boolean {
            // Method body goes here
            return 1==1
        }

        // [OT_AutoGenerated_FROM]: SplitXPath
        // [OT_AutoGenerated_FROM]: SplitXPath
        // [OT_AutoGenerated_HASH]: 39fe2b496ccf044c94f5ce7b56c3ac49016074a297967fecfd7b1d7822eea940
        fun SplitXPath(str: String): List<String> {
            // Method body goes here
            return ArrayList<String>()
        }
}
