class UOM {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: LookUpFromUNCode
        // [OT_AutoGenerated_FROM]: LookUpFromUNCode
        // [OT_AutoGenerated_HASH]: 0e1ea8e617438474356b4ffc8c8cf05ccfd601296c616654a9eb614274c9557c
        fun LookUpFromUNCode(String unCode): UOM {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: IsNullOrEmpty
        // [OT_AutoGenerated_FROM]: IsNullOrEmpty
        // [OT_AutoGenerated_HASH]: 0550de4252b87ee2aab72e743eb7f07e84138bc82f8adbb0484309e449807cb6
        fun IsNullOrEmpty(UOM uom): Boolean {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: ParseFromName
        // [OT_AutoGenerated_FROM]: ParseFromName
        // [OT_AutoGenerated_HASH]: 464f9bc193203079b79a24f2686ceeefb01ba13b17e75f705b4f580fd56eb5c4
        fun ParseFromName(String name): UOM {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: Convert
        // [OT_AutoGenerated_FROM]: Convert
        // [OT_AutoGenerated_HASH]: f579c65a6f093b7cb0898406cdd525bb02d64460ac0fa33cd8640558e046a51c
        fun Convert(Double value, UOM from, UOM to): Double {
            // Method body goes here
        }
}
