class UOMS {
    companion object{
        var List: List<UOM> = "System.Collections.Generic.List`1[OpenTraceability.Utility.UOM]"
    }

        // [OT_AutoGenerated_FROM]: GetBase
        // [OT_AutoGenerated_FROM]: GetBase
        // [OT_AutoGenerated_HASH]: 25c884b5afd1cdde7051ee77a69005695977fe5d9e6c8196766ab09a931dfd84
        fun GetBase(UOM uom): UOM {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: GetUOMFromName
        // [OT_AutoGenerated_FROM]: GetUOMFromName
        // [OT_AutoGenerated_HASH]: ed3747ac6ed1402e79b748d15bb6312d0e89c677cb71972ba6eabed014015968
        fun GetUOMFromName(String Name): UOM {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: GetUOMFromUNCode
        // [OT_AutoGenerated_FROM]: GetUOMFromUNCode
        // [OT_AutoGenerated_HASH]: 6c485585ec572f1ab7f8444e21716aa4b201b5a398fb258cd9b27b79b0a88e9c
        fun GetUOMFromUNCode(String Name): UOM {
            // Method body goes here
        }
}
