package utility
import com.fasterxml.jackson.core.JsonToken
import com.intellij.psi.xml.XmlDocument
import javax.xml.bind.annotation.*
import java.util.*
import java.net.URI
import java.time.OffsetDateTime
class XElementExtensions {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: GetDocumentNamespaces
        // [OT_AutoGenerated_FROM]: GetDocumentNamespaces
        // [OT_AutoGenerated_HASH]: c51dc7e5a90449912088f71b35ea7b15373027a4e491b0df2cfddad61911ffc8
        fun<String> GetDocumentNamespaces(x: XmlDocument): Dictionary<String, String> {
            // Method body goes here
            return Dictionary<String, String>()
        }

        // [OT_AutoGenerated_FROM]: QueryXPath
        // [OT_AutoGenerated_FROM]: QueryXPath
        // [OT_AutoGenerated_HASH]: e8c9e6b08b738b57a9049a419c6309039b0f780b20d1080c92e5b39a96a88555
        fun QueryXPath(x: XmlElement, xpath: String): XmlElement {
            // Method body goes here
            return XmlElement()
        }

        // [OT_AutoGenerated_FROM]: QueryJPath
        // [OT_AutoGenerated_FROM]: QueryJPath
        // [OT_AutoGenerated_HASH]: 8cdd4d0c173deb72a575b5941d74d7048b7b9a8c29e484f19b432fa54bc68a1c
        fun QueryJPath(j: JsonToken, jpath: String): JsonToken {
            // Method body goes here
            return JsonToken()
        }

        // [OT_AutoGenerated_FROM]: AttributeISODateTime
        // [OT_AutoGenerated_FROM]: AttributeISODateTime
        // [OT_AutoGenerated_HASH]: 2adeb44dca16681c9a582cb88eeeab61640952d16f25744b176c3e8588b24258
        fun AttributeISODateTime(x: XmlElement, attName: String): OffsetDateTime? {
            // Method body goes here
            return OffsetDateTime.now()
        }

        // [OT_AutoGenerated_FROM]: AttributeURI
        // [OT_AutoGenerated_FROM]: AttributeURI
        // [OT_AutoGenerated_HASH]: b1ec53a05661a056345fd3e455413ae61841f913ea073be899df8fc2fcf10ce7
        fun AttributeURI(x: XmlElement, attName: String): URI {
            // Method body goes here
            return URI("")
        }

        // [OT_AutoGenerated_FROM]: AttributeBoolean
        // [OT_AutoGenerated_FROM]: AttributeBoolean
        // [OT_AutoGenerated_HASH]: 08287d16f89869e92576bf7d4ed0fdffbd8ff38c739c949960beed74bf82b08f
        fun AttributeBoolean(x: XmlElement, attName: String): Boolean? {
            // Method body goes here
            return 1==1
        }

        // [OT_AutoGenerated_FROM]: AttributeDouble
        // [OT_AutoGenerated_FROM]: AttributeDouble
        // [OT_AutoGenerated_HASH]: 8a042b14e722d72ac1d9a4056d385784c5d569461a98aae15fd4db1142f66f64
        fun AttributeDouble(x: XmlElement, attName: String): Double? {
            // Method body goes here
            return 0.0
        }

        // [OT_AutoGenerated_FROM]: AttributeUOM
        // [OT_AutoGenerated_FROM]: AttributeUOM
        // [OT_AutoGenerated_HASH]: dc1c95ba71c0e2fdd83226315b5a1fff231ed61559418f3277756743eaf07973
        fun AttributeUOM(x: XmlElement, attName: String): UOM {
            // Method body goes here
            return UOM()
        }

        // [OT_AutoGenerated_FROM]: AddStringElement
        // [OT_AutoGenerated_FROM]: AddStringElement
        // [OT_AutoGenerated_HASH]: 3455b5021f6cfc73a0dda5571b6602d7f74b435d74b1c480afa4a26c0b4761b9
        fun AddStringElement(x: XmlElement, xname: XName, value: String) {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: AddDateTimeOffsetISOElement
        // [OT_AutoGenerated_FROM]: AddDateTimeOffsetISOElement
        // [OT_AutoGenerated_HASH]: 183d58bff2b4a5867ae3966ee333230abe372e834f33474531a91b3345fb5abe
        fun AddDateTimeOffsetISOElement(x: XmlElement, xname: XName, value: OffsetDateTime?) {
            // Method body goes here
        }
}
