class XElementExtensions {
    companion object{
    }

        // [OT_AutoGenerated_FROM]: GetDocumentNamespaces
        // [OT_AutoGenerated_FROM]: GetDocumentNamespaces
        // [OT_AutoGenerated_HASH]: c51dc7e5a90449912088f71b35ea7b15373027a4e491b0df2cfddad61911ffc8
        fun GetDocumentNamespaces(XDocument x): Dictionary`2 {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: QueryXPath
        // [OT_AutoGenerated_FROM]: QueryXPath
        // [OT_AutoGenerated_HASH]: e8c9e6b08b738b57a9049a419c6309039b0f780b20d1080c92e5b39a96a88555
        fun QueryXPath(XElement x, String xpath): XElement {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: QueryJPath
        // [OT_AutoGenerated_FROM]: QueryJPath
        // [OT_AutoGenerated_HASH]: 8cdd4d0c173deb72a575b5941d74d7048b7b9a8c29e484f19b432fa54bc68a1c
        fun QueryJPath(JToken j, String jpath): JToken {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: AttributeISODateTime
        // [OT_AutoGenerated_FROM]: AttributeISODateTime
        // [OT_AutoGenerated_HASH]: 2adeb44dca16681c9a582cb88eeeab61640952d16f25744b176c3e8588b24258
        fun AttributeISODateTime(XElement x, String attName): OffsetDateTime? {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: AttributeURI
        // [OT_AutoGenerated_FROM]: AttributeURI
        // [OT_AutoGenerated_HASH]: b1ec53a05661a056345fd3e455413ae61841f913ea073be899df8fc2fcf10ce7
        fun AttributeURI(XElement x, String attName): URI {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: AttributeBoolean
        // [OT_AutoGenerated_FROM]: AttributeBoolean
        // [OT_AutoGenerated_HASH]: 08287d16f89869e92576bf7d4ed0fdffbd8ff38c739c949960beed74bf82b08f
        fun AttributeBoolean(XElement x, String attName): Boolean? {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: AttributeDouble
        // [OT_AutoGenerated_FROM]: AttributeDouble
        // [OT_AutoGenerated_HASH]: 8a042b14e722d72ac1d9a4056d385784c5d569461a98aae15fd4db1142f66f64
        fun AttributeDouble(XElement x, String attName): Double? {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: AttributeUOM
        // [OT_AutoGenerated_FROM]: AttributeUOM
        // [OT_AutoGenerated_HASH]: dc1c95ba71c0e2fdd83226315b5a1fff231ed61559418f3277756743eaf07973
        fun AttributeUOM(XElement x, String attName): UOM {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: AddStringElement
        // [OT_AutoGenerated_FROM]: AddStringElement
        // [OT_AutoGenerated_HASH]: 3455b5021f6cfc73a0dda5571b6602d7f74b435d74b1c480afa4a26c0b4761b9
        fun AddStringElement(XElement x, XName xname, String value): Void {
            // Method body goes here
        }

        // [OT_AutoGenerated_FROM]: AddDateTimeOffsetISOElement
        // [OT_AutoGenerated_FROM]: AddDateTimeOffsetISOElement
        // [OT_AutoGenerated_HASH]: 183d58bff2b4a5867ae3966ee333230abe372e834f33474531a91b3345fb5abe
        fun AddDateTimeOffsetISOElement(XElement x, XName xname, OffsetDateTime? value): Void {
            // Method body goes here
        }
}
